sudo: required
branches:
  only:
  - main
env:
  global:
  # GIT_USER_EMAIL
  - secure: jjQT6gz7xVHr/4GcCsIr8JcuzSWaBwwO9xqfvRYeIBi4bCOhpKlIy4NsowVGvTiFUci5WT1zDwJJ2TYQSADiOP132tusAvc7ox28uJkEzKFLcCerhI/SqL4StbL2UUDsx3B7DPOBhzPe84F+PNplXVG4KpgfU8x7TRt8s8UEassgX6KKVCWfn4Yk+JDhntvFFFjJjEbbZcMh+AmSibhHq5CxYZINSSneUxaR3IgrIScjCa4o1JgaJ9sqosUMr9wjt+R53fVyWKCTQPPx6+R1zBbYNPeL46ao7SipHZfDMMu+E0TIfAQ1J82+BYW/3LoBZ2jiahK3ULxKTe8hwkQKkk4Bmuo+6e4t4cssM3wuFH2X72W+7GDmiF3xdHjWTaC0yUhC0T/bD+C8bp+uaf1O+3GfNDgznD7RwMpJfJCq3rshZlYDl+29PB9bd+a3S0XIZUUCyZLirWU3vlhE9+3Unxo36UTIvfRihsfgldF9WacwTnT0nCzUzUqtFU6Nfl1pF1yUv1p9fQpaNjIgc0s+ClOM/SVYxL8mb/jGSJRJ+ckE7oQQ0c6YsoE31g7KXHHjHUy/Pwemf1e6+vFfYtm4CgTCkqILAHLmffHEtv+/nYFuKWjGlVClyf5rHIVrmF8FNTdHG24RU9P2rYoHN8Qvh/OdAboVLWKRk7C64Vs2xJE=
  # GIT_USER_NAME
  - secure: BiQeaYumQ09rY2bhqBWH1sU4O8l3A6zY+MwRkmebG8JvJTXzBkA68HOYz6fekF/VvITbMKaXf6W8M5umNJCLhkyJnzhK3GaFSd+RMAtE3YFV/XzhCWn9b1QGna2vSBT7APboVMwzN28FUM+rxM6lDAAmromh24zEHQD7K87lD4f4JG/JGRGRcPVbiB/I2rWfwy2eAb0Pjy7PozBUXEYW1jodCZG0Slm9A5mz2vnnUJlSJ22z8EAPIQuXhVtv4SaE3hvpSMFm/7JiUG3sic/0F2G3GzK/B/DuRA42zq4eUOfY08VOthzHF4iNWiHhmmzKBL+2xLsvaesRrTIc2fqWadHWPhzWf32amwE5TpoClEUl1BQuTXNV5Auj11gUDBVB1VpkKT0KaMi7qcIiEx8kloMDia/aAYKc88TYYayIp3VvhCmOFl04mDXl7u8V7kDMLEbWC7e3bQDTtoslXCfhcJHbHb+XCiuAsJ0OVEEClQCbJFFg+AzLzbxlGiiOtQkzCLJeDKNxGYGAs85q88mUPnqNxd18ZOD88AfmlsCn4Km9kV77WRRQ6f41ARlRbPm5QjOPJ2pNEb38QRniyZJJXaS349eqAxPBB1DajcF8c9YtYO2Q5DSNeRbd8z414XS/ypdHsRY/XUNyMjxzHtxpoymbYa+xarhNuqdkd0cKNwc=
  # GIT_UID
  - secure: HzC7oQoZzRzvZpS6YFf3x0l9CGhepcwuFncxcXmijOB4W3Tl57yBExnvVyu8eS7DNrhP1G0wx1b9VhXsjm0tGIXsS2R+Mg7lDz3yu1nBnIdGiZgA8JuRUrZPlb9L8B4VorPReaMPZEXKIKeNR1LifUY+kmJZPUFdumBB0sXEDNIzgv+7HhXdr3t8yCJaaN5SZxc5BHabN+whyaLV+rqj7bCgS47pdiaucEdkGYKEac/9v7gkLFFu2ImYaJx/f3aNEgztXwgaZC11P0eukD2lBM7rFWEDEp//MDAYw0PiudXnh4yIi//BVMci0PW2TsU/oLILwmG2FCwVrSaXfGfVD0eFBQeiDI9Gu3HeyrEIjeQmN8SX5uLQo1neXrUGm+bwsGkyn8ELSwN2SKq4uxIVjJ1ZHCgAMDc4oheGiO7ekTHyFInFi3m6y3i+ZZNJU9wFtwdS6SMTHb+nFHZAOpQT8jARNEvKn8Z2BaFqGvZkpvKaq7pyJI7KwwRPQZ8HqKwndBCtQlmcP5rPqZrBxNNEYpKtakSrKIjCafFPCeGLvFwNUIj3MI8/fdvJCF4r0t9/VUW6KJOGtqCYgaDttd61onLeUM65aEzvaagCjcShUIhNrAMkju/yv3EMPE5TaqRcea1gjtZDRlPyA+IdUogaxH/83gmXvKgWdKTRg7qHAd8=
  # GIT_TOKEN
  - secure: KNhbrPpDzad565uVIUdQoNIhzhoSuDErrf3sF8r6Xc+xq6J6KPV/JPFZcZMs3QUjyAfMKgzPvOdfkdpbVTf8s4bJnWoN9mfJN4STW8O6Cj+wOyMu0EzSZa5rSVGU4ccG3QFJWH4DRaN8e1w/fPeAZYWMUARr/LqTg1b1D0dX2itf5U4V5Bz1XRUR2uv26KKVvaU0HMHzOYxd8Pa+kMAwNrKDDyK3U0PsPqmZBvNcQBjboGNSfltnFYnvrFSaeKN5Z1l3qtGnTqRVJwOIRE1SDDL8vfrLVjJ1hHvkoKPEJ2jkqYXNYuplDyf8mul7Qu5Jvbm+e/zI7D5btcgbumMQ1RKTpLO4blS4ZPGpILYPg5puo1k3rP0tr4J6PlJQ1A9FgdbFroOO2YsiSEuNzQsEXdJcpTNihTJMEkAeqiUW3/+2gYgT61dUdFyX341dS5HIwa42e87Lr8ZUC6ka1yyLtty1YqlDhtFTMC8Q/Gqw8ww3pT1+j/UbMdggHYJrYKEY4MPODiEoZ+7ick3EvxZKbVn2W1CmGG4vVu7CFlbN81y/73OW5u27ZjIMFQ7LlIsIUVBDptEvYsqxdLB5yFmMD6OT1OLancFo5uiLSecstFuNuPiendi0YfFWIAa9I9SyEgToP60ZEg4iKGsSXPS5tLFQgryYNpKNlJoy/+OGs1I=
notifications:
  email:
  - "{GIT_USER_EMAIL}"

services:
- docker
before_install:
- mkdir -p output
- docker pull asciidoctor/docker-asciidoctor
script:
- GUIDE_VERSION=`cat VERSION`"-${TRAVIS_BUILD_NUMBER}"
- echo ${GUIDE_VERSION}
- docker run -v $TRAVIS_BUILD_DIR:/documents/ --name asciidoc-to-html asciidoctor/docker-asciidoctor      asciidoctor
  -a toc=left -a docinfo=shared -D /documents/output DAP4.adoc
after_error:
- docker logs asciidoc-to-html
after_failure:
- docker logs asciidoc-to-html
after_success:
- ./travis/deploy_to_gh_pages.sh
